version: "3.9"

services:
  api:
    image: ghcr.io/nephrogo/nephrogo-api:latest
    env_file:
      - secrets/.env
    labels:
      - lt.nephrogo.api
    healthcheck:
      test: [ "CMD-SHELL", "curl -sSf http://localhost:8080/health/?format=json || exit 1" ]
    stop_grace_period: 60s
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        failure_action: rollback
        order: start-first
    volumes:
      - static_volume:/srv/nephrogo-api/static
      - media_volume:/srv/nephrogo-api/media
      - /srv/nephrogo-api/secrets:/srv/nephrogo-api/secrets
    networks:
      - nginx_network
      - database_network
      - redis_network
      - datadog_network

  celery_beat:
    image: ghcr.io/nephrogo/nephrogo-api:latest
    command: ddtrace-run celery -A nephrogo beat -l info --schedule=/srv/nephrogo-api/celerybeat-schedule
    env_file:
      - secrets/.env
    labels:
      - lt.nephrogo.celery.beat
    stop_grace_period: 60s
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
        order: start-first
    volumes:
      - static_volume:/srv/nephrogo-api/static
      - media_volume:/srv/nephrogo-api/media
      - /srv/nephrogo-api/secrets:/srv/nephrogo-api/secrets
    networks:
      - nginx_network
      - database_network
      - redis_network
      - datadog_network

  celery_default_worker:
    image: ghcr.io/nephrogo/nephrogo-api:latest
    command: ddtrace-run celery -A nephrogo worker -l info -E --concurrency=3
    env_file:
      - secrets/.env
    labels:
      - lt.nephrogo.celery.worker
    stop_grace_period: 60s
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
        order: start-first
    volumes:
      - static_volume:/srv/nephrogo-api/static
      - media_volume:/srv/nephrogo-api/media
      - /srv/nephrogo-api/secrets:/srv/nephrogo-api/secrets
    networks:
      - nginx_network
      - database_network
      - redis_network
      - datadog_network

  postgres:
    image: postgres:13.2
    env_file:
      - secrets/.env
    networks:
      - database_network
      - datadog_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
    labels:
      - lt.nephrogo.postgres
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:6.0
    networks:
      - redis_network
      - datadog_network
    labels:
      - lt.nephrogo.redis
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]

  nginx:
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/nephrogo-api/nginx/conf.d:/etc/nginx/conf.d
      - /srv/nephrogo-api/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/srv/nephrogo-api/static
      - media_volume:/srv/nephrogo-api/media
    networks:
      - nginx_network
      - datadog_network
    labels:
      - lt.nephrogo.nginx

  ddagent:
    image: datadog/agent:7
    environment:
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
    env_file:
      - secrets/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - datadog_network

networks:
  nginx_network:
    driver: overlay
  database_network:
    driver: overlay
  redis_network:
    driver: overlay
  datadog_network:
    driver: overlay

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redis_volume:
